# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31f87652782239e96bd6dd43153dc9849be0312623a31a5ad1601a9ded446fc44a9a20752cf9060a641094142d55173ebd750be64873bb8f82f403f851df8b7c

test:
  secret_key_base: 494108b06c33662b861ebb4a13016b33eaa705e6a0b7f99b5b913bf5a36b6bff3a26bd60b3d2e960fb9817cb5dc1205225b49b30b9cab19d572692dc4b264506

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
